# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7637d7c2caff7803a8439d825003346c060030f52668edf21b1777d3e1814608c293d5071866bb274a033c728ac51e8e4ae87d2744d950ae43313eec77a41314

test:
  secret_key_base: cc8e67b6372590c59c53154774a1ebb6411e6ffdcc6a65082cc067066f16be9d09d416988c32c37256840f26888490fc91e727fdb1737dac04073c8e92d4041d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
