# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bdddf0c7ae831f6b9c6b79272c054935c8958b88239a661f473e554149c044aa3f796bab6df9d52121989f3cf5dd79de73860c22cd40e495422c48b400d84a4c

test:
  secret_key_base: 1e52154f224cd20a024165d5efaa65199d24d7c37ce5e5db3505c12bbba0045e94ec44b43dfc8545788000f34734db4768cba58b3eaf5371c1fec7bd51035ba4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
